import Head from 'next/head';
import Header from '@/components/Header';
import Content from '@/components/Content';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-24">
        <Header />
        <Content />
      </main>
    </div>
  );
}
